# Generated by Django 5.0.1 on 2024-02-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_variacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variável', 'verbose_name_plural': 'Variações'},
        ),
    ]
